#!/bin/bash

## usage
echo "vm_network_setup <host> <ip> <gateway> <MAC>"

echo Host is $1
echo IP is $2
echo gateway is $3
echo MAC is $4

yum remove -y NetworkManager

rm -f /etc/sysconfig/network

echo 'NETWORKING=yes
HOSTNAME='$1'
GATEWAY='$3 >> /etc/sysconfig/network

rm -f /etc/sysconfig/network-scripts/ifcfg-eth0

echo 'DEVICE="eth0"
HWADDR='$4'
TYPE=Ethernet
BOOTPROTO=none
IPADDR0='$2'
PREFIX0=24
GATEWAY0='$3'
DNS1='$3'
DEFROUTE=yes
IPV4_FAILURE_FATAL=yes
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
NAME="System eth0"
ONBOOT=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth0

chkconfig network off
chkconfig network on
systemctl restart network

echo "checking connectivity"
ping www.google.com
