#!/bin/bash

## usage
echo "vm_network_setup <host> <ip> <gateway> <MAC>"

echo Host is $1
echo IP is $2
echo gateway is $3
echo MAC is $4

yum remove -y NetworkManager

rm -f /etc/sysconfig/network

echo 'NETWORKING=yes
HOSTNAME='$1'
GATEWAY='$3 >> /etc/sysconfig/network

rm -f /etc/sysconfig/network-scripts/ifcfg-eth0

echo 'DEVICE="eth0"
HWADDR='$4'
TYPE=Ethernet
BOOTPROTO=none
IPADDR='$2'
PREFIX=24
GATEWAY='$3'
DNS1='$3'
DEFROUTE=yes
IPV4_FAILURE_FATAL=yes
IPV6INIT=no
NAME="System eth0"
ONBOOT=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth0

rm -f /etc/udev/rules.d/70-persistent-net.rules
echo 'SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="'$4'", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"' >> /etc/udev/rules.d/70-persistent-net.rules

start_udev
/etc/init.d/network restart

echo "checking connectivity"
ping www.google.com
